# -*- coding: utf-8 -*-
"""Mubazirver4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pU2Stwdwb9OQ9eA-Y86ONz1g5HREy5w3
"""

!pip install -q kaggle

from google.colab import files
files.upload()

!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d 'swoyam2609/fresh-and-stale-classification'

import zipfile
dataset_zip = zipfile.ZipFile('/content/fresh-and-stale-classification.zip', 'r')
dataset_zip.extractall()
dataset_zip.close()

base_dir = '/content/dataset'

train_dir = '/content/dataset/Train'
test_dir = '/content/dataset/Test'

import os

total_train = 0

for i in os.listdir(train_dir):
  total_train += len(os.listdir(train_dir+'/'+i))
  print('Total File ', i, '=', len(os.listdir(train_dir+'/'+ i)))

print(total_train)

total_test = 0

for i in os.listdir(test_dir):
  total_test += len(os.listdir(test_dir+'/'+i))
  print('Total File ', i, '=', len(os.listdir(test_dir+'/'+ i)))

print(total_test)


total = 0
total = total_train + total_test
print('Total dataset = ', total)



!rm -r /content/dataset/Train/freshbittergroud
!rm -r /content/dataset/Train/rottenbittergroud
!rm -r /content/dataset/Train/freshcapsicum
!rm -r /content/dataset/Train/rottencapsicum
!rm -r /content/dataset/Test/.ipynb_checkpoints

!mv /content/dataset/Test/freshtamto /content/dataset/Test/freshtomato
!mv /content/dataset/Test/freshpatato /content/dataset/Test/freshpotato
!mv /content/dataset/Test/rottenpatato /content/dataset/Test/rottenpotato
!mv /content/dataset/Test/rottentamto /content/dataset/Test/rottentomato

os.listdir(train_dir)

os.listdir(test_dir)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random

def view_random_image (target_dir, target_class):
  target_folder = target_dir + target_class
  random_image = random.sample(os.listdir(target_folder),1)

  img = mpimg.imread(target_folder + '/' + random_image[0])
  plt.imshow(img)
  plt.title(target_class)
  plt.axis('off')

  print(f"Ukuran gambar : {img.shape}")
  return img

img = view_random_image (train_dir, '/rottenbanana')

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPool2D, Activation
from tensorflow.keras import Sequential
from tensorflow.keras.callbacks import ModelCheckpoint

train_datagen = ImageDataGenerator(
    rescale=1./255,
)
val_datagen = ImageDataGenerator(
    rescale=1./255,

)

train_data_rf = train_datagen.flow_from_directory(
    train_dir,
    batch_size = 15,
    target_size = (150,150),
    class_mode = "categorical"
)
val_data_rf = val_datagen.flow_from_directory(
    test_dir,
    batch_size = 15,
    target_size = (150,150),
    class_mode = "categorical"
)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(150, 150, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(14, activation='softmax')
])

# Print the model summary
model.summary()

model.compile(loss = 'categorical_crossentropy', optimizer = 'adamax',   metrics=['accuracy'])

hist = model.fit(
    train_data_rf,
    epochs = 15,
    validation_data=val_data_rf
)

import matplotlib.pyplot as plt

# Plot the results
acc = hist.history['accuracy']
val_acc = hist.history['val_accuracy']
loss = hist.history['loss']
val_loss = hist.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'r', label='Training accuracy')
plt.plot(epochs, val_acc, 'b', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.legend(loc=0)
plt.figure()

plt.show()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
from google.colab import files
from tensorflow.keras.utils import load_img, img_to_array

# %matplotlib inline
uploaded = files.upload()

for fn in uploaded.keys():
  path = fn
  img = load_img(path, target_size=(150, 150))
  x = img_to_array(img)
  x = np.expand_dims(x, axis=0)
  x = x/.255

  images = np.vstack([x])
  arr = model.predict(images, batch_size=10)

# Mengambil indeks kelas dengan nilai probabilitas tertinggi
predicted_class_index = np.argmax(arr)

# Daftar label yang sesuai dengan indeks kelas
class_labels = [
    'Fresh Apples', 'Fresh Banana', 'Fresh Cucumber', 'Fresh Okra',
    'Fresh Oranges', 'Fresh Potato', 'Fresh Tomato',
    'Rotten Apples', 'Rotten Banana', 'Rotten Cucumber',
    'Rotten Okra', 'Rotten Oranges', 'Rotten Potato', 'Rotten Tomato'
]

# Menentukan label
predicted_label = class_labels[predicted_class_index]

# Menampilkan hasil prediksi
print('{} is a {}'.format(fn, predicted_label))



import keras
from tensorflow.keras.models import save_model

# Calling save('my_model.keras') creates a zip archive my_model.keras.
model.save("mubazirver4.h5")

from google.colab import files
files.download('mubazirver4.h5')